CREATE FUNCTION `programmingQuestion`(q VARCHAR(100), r TEXT, u TEXT) RETURNS int
BEGIN

	INSERT INTO CONVERSATION (CONVERSATION_QUESTION, CONVERSATION_QUESTION_TIME, CONVERSATION_RESPONSE, CONVERSATION_URL)
	VALUES (q, CURRENT_TIMESTAMP, r, u);
    
RETURN LAST_INSERT_ID();
END