-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CONVERSATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONVERSATION` (
  `CONVERSATION_ID` INT NOT NULL AUTO_INCREMENT,
  `CONVERSATION_QUESTION` TEXT NOT NULL,
  `CONVERSATION_QUESTION_TIME` TIMESTAMP NOT NULL,
  `CONVERSATION_SUCCESS` TINYINT(1) NULL,
  `CONVERSATION_RESPONSE` TEXT NULL,
  PRIMARY KEY (`CONVERSATION_ID`),
  UNIQUE INDEX `MESSAGE_ID_UNIQUE` (`CONVERSATION_ID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
